</div>
<div class="container text-center">
	<hr>
	Plataforma Experts Learning Projeto &copy; Todos os Direitos Reservados - <?=date('Y');?>
</div>
<?php if(\Plataforma\Session\Session::has('pagseguro_session')):?>

    <script src="https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>
    <script>
        const sessionId = '<?=\Plataforma\Session\Session::get('pagseguro_session');?>';

        PagSeguroDirectPayment.setSessionId(sessionId);
    </script>

<?php endif;?>
<script
        src="https://Plataforma.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>