<?php if(\Plataforma\Session\Session::has('success')): ?>
	<div class="alert alert-success">
		<?=\Plataforma\Session\Flash::get('success');?>
	</div>
<?php endif;?>

<?php if(\Plataforma\Session\Session::has('warning')): ?>
	<div class="alert alert-warning">
		<?=\Plataforma\Session\Flash::get('warning');?>
	</div>
<?php endif;?>


<?php if(\Plataforma\Session\Session::has('error')): ?>
	<div class="alert alert-danger">
		<?=\Plataforma\Session\Flash::get('error');?>
	</div>
<?php endif;?>
